[[bond]]
source = "tpknam1qqljnd0w23luk2g42s5uy0y4f0zmz6ajtc7l49xwgwyc0argu20eye6pdan"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "130"

[bond.signatures]
tpknam1qqljnd0w23luk2g42s5uy0y4f0zmz6ajtc7l49xwgwyc0argu20eye6pdan = "signam1qqw5g8vgeag8fta0ky0t9wwsykjd84ancy8t3ngwg04z8hg8g0z3d3aw6qky6mg45p56yaqcxvksvsy5tvnxvz3rzdwux5qjug2ux8q93747sw"
